Indir: "/Path/raw_counts_for_deseq2.txt"
Outdir: "/Path/DEseq2_output"
MetaData: "/Path/metaInfo.tsv"
smallestGroupSize: 5 # minimum no. of samples per group
DeseqEnv: "envs/env_deseq2.yaml"
Type: "" # specify if it is smallRNAs